version: "1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    volumes:
      - pg_vol:/var/lib/postgresql/data

volumes:
  pg_vol: